apiVersion: scope.github.com/v1alpha
kind: ScopeDoctorSetup
metadata:
  name: setup
spec:
  cache:
    paths:
      - '**/requirements.txt'
  setup:
    exec:
      - ../bin/pip-install.sh
  description: You need to run bin/setup