apiVersion: scope.github.com/v1alpha
kind: ScopeDoctorGroup
metadata:
  name: group-1
  description: Check your shell for basic functionality
spec:
  actions:
    - description: foo1
      name: fail then pass
      check:
        commands:
          - ./scripts/fail-first-call foo
      fix:
        commands:
          - ../bin/pip-install.sh
    - description: sleep
      name: "sleep"
      check: { }
      fix:
        commands:
          - sleep 1
    - description: foo2
      name: paths
      check:
        paths:
          - '**/requirements.txt'
