apiVersion: scope.github.com/v1alpha
kind: ScopeDoctorGroup
metadata:
  name: path-exists
  description: Check your shell for basic functionality
spec:
  actions:
    - description: foo1
      check:
        commands:
          - ./scripts/fail-first-call path-exists
      fix:
        commands:
          - ../bin/truey
