apiVersion: scope.github.com/v1alpha
kind: ScopeDoctorGroup
metadata:
  name: path-exists-fix-in-scope-dir
  description: Check your shell for basic functionality
spec:
  actions:
    - description: foo1
      check:
        commands:
          - ./scripts/fail-first-call path-exists-fix-in-scope-dir
      fix:
        helpText: You're shell does not have a path env. Reload your shell.
        commands:
          - ./scripts/truey
