apiVersion: scope.github.com/v1alpha
kind: ScopeDoctorGroup
metadata:
  name: group-1
  description: Check your shell for basic functionality
spec:
  actions:
    - description: foo1
      check:
        commands:
          - ./scripts/fail-first-call foo
      fix:
        commands:
          - ../bin/pip-install.sh
    - description: foo2
      check:
        paths:
          - '**/requirements.txt'
