apiVersion: scope.github.com/v1alpha
kind: ScopeDoctorSetup
metadata:
  name: setup
spec:
  cache:
    paths:
      - flig/bar/**/*
  setup:
    exec:
      - bin/setup
  description: You need to run bin/setup