---
apiVersion: pity.github.com/v1alpha
kind: PityReport
metadata:
  name: report
spec:
  additionalData:
    env: env
    username: id -u
    ruby: which ruby
    node: which node
    nodeVersion: node -v
  destination:
    rustyPaste:
      url: http://localhost:8000
---
apiVersion: pity.github.com/v1alpha
kind: PityReport
metadata:
  name: github
spec:
  destination:
    githubIssue:
      owner: ethankhall
      repo: dummy-repo