apiVersion: pity.github.com/v1alpha
kind: ExecCheck
metadata:
  name: path-exists
spec:
  target: scripts/does-path-env-exist.sh
  description: Check your shell for basic functionality
  help-text: You're shell does not have a path env. Reload your shell.