[package]
name = "scope-report"
version = "2024.2.3"
edition = "2021"


[dependencies]
clap = { version = "4.4", features = ["derive", "env"]}
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
scope-lib = { path = "../scope-lib" }
