[package]
name = "scope-analyze"
version = "2024.2.3"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.4", features = ["derive", "env"]}
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
scope-lib = { path = "../scope-lib" }
