name: Build Darwin Artifacts

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-for-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - name: Build artifacts
        run: |
          .github/bin/build-macos.sh ${{ inputs.version }}
      - name: Create archive
        run: |
          tar -C target/universal-apple-darwin/release/ -cvzf target/pity-darwin.tgz pity pity-intercept
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: darwin
          path: target/pity-darwin.tgz
          if-no-files-found: error
