name: Build Darwin Artifacts

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-for-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - name: Build artifacts
        run: |
          .github/bin/build-macos.sh ${{ inputs.version }}
      - name: Create archive
        run: |
          tar -C target/universal-apple-darwin/release/ -cvzf target/scope-${{ inputs.version }}-darwin.tgz scope scope-intercept
          shasum -a 256 target/scope-${{ inputs.version }}-darwin.tgz > target/scope-${{ inputs.version }}-darwin.tgz.sha256
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-darwin
          path: |
            target/scope-${{ inputs.version }}-darwin.tgz
            target/scope-${{ inputs.version }}-darwin.tgz.sha256
          if-no-files-found: error
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - name: Build artifacts
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          .github/bin/build-linux.sh ${{ inputs.version }}
      - name: Create archive
        run: |
          .github/bin/create-packages-linux.sh ${{ inputs.version }}
      - name: sign artifacts
        run: |
          echo $COSIGN_PRIVATE_KEY | wc
          echo COSIGN_PASSWORD | wc
          echo '${{ secrets.COSIGN_PRIVATE_KEY }}' > cosign.key
          for FILE in artifacts/*.{rpm,deb,tgz}; do
            cosign sign-blob --yes --key cosign.key "${FILE}" --bundle "${FILE}.bundle"
          done
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: release-linux
          path: |
            target/upload/scope-${{ inputs.version }}-x86_64-unknown-linux-gnu.tgz
            target/upload/scope-${{ inputs.version }}-x86_64-unknown-linux-gnu.tgz.sha256
            target/upload/scope-${{ inputs.version }}-aarch64-unknown-linux-gnu.tgz
            target/upload/scope-${{ inputs.version }}-aarch64-unknown-linux-gnu.tgz.sha256
            target/upload/scope-${{ inputs.version }}-1.aarch64.rpm
            target/upload/scope-${{ inputs.version }}-1.aarch64.rpm.sha256
            target/upload/scope-${{ inputs.version }}-1.x86_64.rpm
            target/upload/scope-${{ inputs.version }}-1.x86_64.rpm.sha256
            target/upload/scope_${{ inputs.version }}_amd64.deb
            target/upload/scope_${{ inputs.version }}_amd64.deb.sha256
            target/upload/scope_${{ inputs.version }}_arm64.deb
            target/upload/scope_${{ inputs.version }}_arm64.deb.sha256
          if-no-files-found: error
