name: Continuous integration
on:
  # Defining workflow_call means that this workflow can be called from
  # your main workflow job
  workflow_call:
    # cargo-dist exposes the plan from the plan step, as a JSON string,
    # to your job if it needs it
    inputs:
      plan:
        required: true
        type: string

jobs:
  linux-arm:
    name: Build Linux ARM Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - name: cargo build
        run: .github/bin/build-with-cross.sh aarch64-unknown-linux-gnu
      - name: Upload ARM Linux
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-build-local-aarch64-unknown-linux-gnu
          path: |
            target/dev-scope-aarch64-unknown-linux-gnu.tar.xz
          if-no-files-found: error
