name: Create release and publish artifacts

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      release-options:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      COSIGN_PRIVATE_KEY:
        description: 'Used sign artifacts'
        required: true
      COSIGN_PASSWORD:
        description: 'Used to unlock the secret'
        required: true

concurrency:
  group: ${{ github.workflow }}-release-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-for-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    with:
      version: ${{ inputs.version }}

  create-release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs:
      - build-for-artifacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: release-*
          path: artifacts
          merge-multiple: true
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
      - name: sign artifacts
        run: |
          echo '${{ secrets.COSIGN_PRIVATE_KEY }}' > cosign.key
          for FILE in artifacts/*.{rpm,deb,tgz}; do
           cosign sign-blob --yes --key cosign.key "${FILE}" --bundle "${FILE}.bundle"
          done
        env:
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
      - name: create-release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          set -eux
          gh release create --repo ${GITHUB_REPOSITORY} ${{ inputs.version }} --generate-notes ${{ inputs.release-options }} --target ${GITHUB_SHA} artifacts/*
