name: Generate DotSlash files

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  generate-dotslash-files:
    name: Generating and uploading DotSlash files
    runs-on: ubuntu-latest
    steps:
      - name: Get release tag
        id: version
        run: |
          VERSION="$(echo "$PLAN" | jq --compact-output '.announcement_tag')"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
      - uses: facebook/dotslash-publish-release@v1
        # This is necessary because the action uses
        # `gh release upload` to publish the generated DotSlash file(s)
        # as part of the release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Additional file that lives in your repo that defines
          # how your DotSlash file(s) should be generated.
          config: .github/workflows/dotslash-config.json
          # Tag for the release to to target.
          tag: ${{ steps.version.outputs.version }}