name: Build Github Pages

on:
  workflow_call:
  pull_request:
    paths:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gh-pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build docs

      - run: |
          tar \
              --dereference --hard-dereference \
              --directory "docs/book" \
              -cvf "$RUNNER_TEMP/artifact.tar" \
              .

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: ${{ inputs.retention-days }}
          if-no-files-found: error

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        if: ${{ github.ref == 'refs/heads/main' }}
